workflows:
  ios-workflow:
    name: iOS Build
    max_build_duration: 60
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Expo prebuild
        script: npx expo prebuild --platform ios
      - name: Build iOS
        script: |
          xcodebuild -workspace ios/MotsSecrets.xcworkspace \
            -scheme MotsSecrets \
            -configuration Release \
            -sdk iphonesimulator \
            -derivedDataPath build
    artifacts:
      - build/**/*.app